- name: runs web server roles
  hosts: webserver
  become: true
  vars_files:
    - ./group_vars/web.yml
    - ./group_vars/db.yml
  roles:
    - { role: base, tags: base }
    - { role: users, tags: users }
    - { role: webserver, tags: webserver }
    - { role: database, tags: database }
    - { role: app_deploy, tags: app_deploy }
