- name: is bundler exist
  command: gem list -i bundler
  register: is_bundler_exist
- name: install bundler
  command: gem install bundler
  changed_when: is_bundler_exist == false
- name: create app directory
  file:
    path: /srv/app
    owner: deployer
    group: www-data
    state: directory
    mode: 02755
    recurse: yes
- name: clone repo
  become_user: deployer
  git:
    repo: https://github.com/salmanhoque/code_pipeline_build_deploy.git
    dest: /srv/app
    force: yes
- name: install all required gems
  become_user: deployer
  bundler:
    state: present
    chdir: /srv/app
- name: create assets
  become_user: deployer
  command: /bin/bash -lc "bundle exec rake assets:precompile"
  args:
    chdir: /srv/app
- name: run migration
  become_user: deployer
  command: /bin/bash -lc "bundle exec rake db:migrate"
  args:
    chdir: /srv/app
- name: run application
  become_user: deployer
  command: /bin/bash -lc "bundle exec unicorn -c config/unicorn.rb -E production -D"
  args:
    chdir: /srv/app
