- name: install PostgreSQL
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
- name: ensure the PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes
- name: create database user
  become_user: postgres
  postgresql_user:
    name: "{{ vault_databse_user }}"
    password: "{{ vault_database_password }}"
    state: present
- name: create database
  become_user: postgres
  postgresql_db:
    owner: "{{ vault_databse_user }}"
    name: aws_code_production
    encoding: UTF-8
- name: give privillege to db user
  become_user: postgres
  postgresql_privs:
    db: aws_code_production
    privs: ALL
    type: database
    role: "{{ vault_databse_user }}"
